language: clojure
jdk:
  - oraclejdk11

install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.469.sh
  - chmod +x linux-install-1.10.1.469.sh
  - sudo ./linux-install-1.10.1.469.sh
  - rm linux-install-1.10.1.469.sh

script:
  - make test
  - make uberjar
  - cd example && make build && cd ..
  - make deploy

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cljs
    - $HOME/.gitlibs
    - .cpcache

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: example/build
  on:
    branch: master
